force-app/main/default/objects/Invoices__c/Invoices__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoices__c/fields/AmountWithVat__c.field-meta.xml
<CustomField>
    <fullName>AmountWithVat__c</fullName>
    <formula>(AmountWithoutVat__c * Vat__c )+AmountWithoutVat__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount With Vat</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoices__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <label>Invoice date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Invoices__c/fields/InvoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>InvoiceNumber__c</fullName>
    <label>Invoice Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/classes/LC03_RetrieveInvoicesToCase.cls
/**
 * @description       : 
 * @author            : Asma Ghanty
 * @group             : 
 * @last modified on  : 10-28-2022
 * @last modified by  : Asma Ghanty
 * Modifications Log
 * Ver   Date         Author        Modification
 * 1.0   10-28-2022   Asma Ghanty   Initial Version
**/
public with sharing class LC03_RetrieveInvoicesToCase {
    @AuraEnabled 
    public static List <Invoices__c> getRelatedInvoices(String caseIdToSearch){
       
        List<Invoices__c> lstInvoices = [SELECT Case__c, InvoiceNumber__c, InvoiceDate__c, Account__c, 
                                            AmountWithVat__c, Contact__c, AmountWithoutVat__c FROM Invoices__c 
                                            WHERE Case__c =: caseIdToSearch ORDER BY CreatedDate DESC];
        return lstInvoices;

   
}
}