force-app/main/default/objects/Invoices__c/Invoices__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoices__c/fields/AmountWithVat__c.field-meta.xml
<CustomField>
    <fullName>AmountWithVat__c</fullName>
    <formula>(AmountWithoutVat__c * Vat__c )+AmountWithoutVat__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount With Vat</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoices__c/fields/CaseAssignedTo__c.field-meta.xml
<CustomField>
    <fullName>CaseAssignedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case Assigned To</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Invoices</relationshipLabel>
    <relationshipName>Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoices__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <label>Invoice date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/LC01_DisplayInvoicesControllerTest.cls
/**
 * @description       : 
 * @author            : Jason Ramjaya
 * @group             : 
 * @last modified on  : 11-08-2022
 * @last modified by  : Jason Ramjaya
**/
@isTest
public with sharing class LC01_DisplayInvoicesControllerTest {

    @testSetup public static void testSetup() {

        List<User> lstUser = AP_TestDataFactory.createUsers(1);
        insert lstUser;
        System.debug('User:'+lstUser[0].Id);

        System.runAs(lstUser[0]) {
            List<Account> testAcList =  AP_TestDataFactory.createAccounts(1);
            insert testAcList;
            System.debug('Acc:'+testAcList[0].Id);

            List<Case> testCaseList =  AP_TestDataFactory.createCases(1);
            for(Case cas:testCaseList) {
                cas.AccountId = testAcList[0].Id;
            }
            insert testCaseList;
            System.debug(testCaseList[0].Id);

            List<Invoices__c> testInvList = AP_TestDataFactory.createInvoices(1);
            for(Invoices__c inv: testInvList) {
                inv.Account__c = testAcList[0].Id;
                inv.CaseAssignedTo__c = testCaseList[0].Id;
            }
            insert testInvList;
            System.debug(testInvList[0].Id);
        }
    }

    @isTest public static void testInvoiceList() {



        List<Invoices__c> lstInvoices = new List<Invoices__c>();
        List<Case> lstCases = new List<Case>();
        List<User> lstUsers = [SELECT Id, name FROM USER WHERE LastName LIKE 'Testing%' LIMIT 1];
        

        System.runas(lstUsers[0]) {
            Test.startTest();

            lstCases = [SELECT Id FROM Case WHERE Status = 'New'];
            System.debug(lstCases);

            lstInvoices = LC01_DisplayInvoicesController.getInvoices(lstCases[0].Id);
            List<Invoices__c> lstInvoices2 = [
            SELECT Name, InvoiceDate__c, Account__c, AmountWithVat__c, Contact__c,
            AmountWithoutVat__c 
            FROM Invoices__c 
            WHERE CaseAssignedTo__c =: lstCases[0].Id
            ORDER BY CreatedDate DESC];
            //List<Invoices__c> lstInvoices3 = LC01_DisplayInvoicesController.getInvoices('124');
            Test.stopTest();

            System.debug(lstInvoices);

            //System.assertEquals(null, lstInvoices3, 'Hmm, what is happening?');
            System.assertEquals(lstInvoices2, lstInvoices, 'Identical list expected');
            System.assertEquals(1, lstInvoices.size(), 'Only one invoice expected');

        }
  
    }
}