force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Engine_capacity__c.field-meta.xml
<CustomField>
    <fullName>Engine_capacity__c</fullName>
    <label>Engine capacity</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/InsuranceEndDate__c.field-meta.xml
<CustomField>
    <fullName>InsuranceEndDate__c</fullName>
    <label>Insurance End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/InsuranceStartDate__c.field-meta.xml
<CustomField>
    <fullName>InsuranceStartDate__c</fullName>
    <label>Insurance Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/InsuredTo__c.field-meta.xml
<CustomField>
    <fullName>InsuredTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Insured to</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>VehicleInsured</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/AP01_SelectDetailLoan.cls
/**
 * @description       : 
 * @author            : Mehreen Jhummun
 * @group             : 
 * @last modified on  : 03/11/2022
 * @last modified by  : Mehreen Jhummun
 * Modifications Log
 * Ver   Date         Author            Modification
 * 1.0   03/11/2022   Mehreen Jhummun   Initial Version
**/
public with sharing class AP01_SelectDetailLoan {
    @AuraEnabled(cacheable=true)
    public static List<Case> displayDetailsLoan(String caseid) {
    

        List<Case> lstcaseAllVehicle=[SELECT Id,Vehicle__c,
                                    Vehicle__r.Engine_capacity__c,
                                    Vehicle__r.Name,   
                                    Vehicle__r.InsuranceEndDate__c, 
                                    Vehicle__r.InsuranceStartDate__c, 
                                    Vehicle__r.InsuredTo__c, 
                                    Vehicle__r.InsuredTo__r.Active__c,
                                    Vehicle__r.RecordType.DeveloperName
                                    FROM Case 
                                    WHERE Vehicle__c !=NULL AND Id=:caseid AND Vehicle__r.RecordType.Name='Loaned Vehicle'];
        return lstcaseAllVehicle;
    

}
}