force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/InsuranceEndDate__c.field-meta.xml
<CustomField>
    <fullName>InsuranceEndDate__c</fullName>
    <label>Insurance End Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/InsuranceStartDate__c.field-meta.xml
<CustomField>
    <fullName>InsuranceStartDate__c</fullName>
    <label>Insurance Start Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/RegistrationNumber__c.field-meta.xml
<CustomField>
    <fullName>RegistrationNumber__c</fullName>
    <externalId>true</externalId>
    <label>Registration number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AP01_displayListOfVehicle.cls
/**
 * @description       : 
 * @author            : Bhavish Nundoo
 * @group             : 
 * @last modified on  : 11-04-2022
 * @last modified by  : Bhavish Nundoo
 * Modifications Log
 * Ver   Date         Author           Modification
 * 1.0   11-04-2022   Bhavish Nundoo   Initial Version
**/
public with sharing class AP01_displayListOfVehicle {
    @AuraEnabled
  public static List<Vehicle__c> getVehicle(Id recordId) {
  return [SELECT Model__c, RegistrationNumber__c, InsuranceStartDate__c, InsuranceEndDate__c,Contact__r.Id  FROM Vehicle__c Where Contact__r.Id!= Null AND Contact__r.Id=:recordId];
  }
}