force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/LoanedTo__c.field-meta.xml
<CustomField>
    <fullName>LoanedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Loaned to</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Vehicles (Loaned to)</relationshipLabel>
    <relationshipName>VehicleLoaned</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/LoanEndDate__c.field-meta.xml
<CustomField>
    <fullName>LoanEndDate__c</fullName>
    <label>Loan End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/LoanStartDate__c.field-meta.xml
<CustomField>
    <fullName>LoanStartDate__c</fullName>
    <label>Loan start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>available</fullName>
            </value>
            <value>
                <fullName>loaned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/recordTypes/LoanedVehicle.recordType-meta.xml
<RecordType>
    <fullName>LoanedVehicle</fullName>
    <active>true</active>
    <label>Loaned Vehicle</label>
</RecordType>

force-app/main/default/classes/LoanedVehicleDetailsController.cls
/**
 * @description       : 
 * @author            : Chevish Boodhun
 * @group             : 
 * @last modified on  : 11-03-2022
 * @last modified by  : Chevish Boodhun 
 * Modifications Log
 * Ver   Date         Author            Modification
 * 1.0   11-03-2022   Chevish Boodhun   Initial Version
**/
public with sharing class LoanedVehicleDetailsController {

    @AuraEnabled
    public static void removeLoanedVehicle(Id caseId, Id vehicleId) {
        
        Case currentCase = [SELECT Id FROM Case WHERE Id = :caseId];
        Vehicle__c loanedVehicle = [SELECT Id FROM Vehicle__c WHERE Id = :vehicleId];

        if (currentCase != null) {
            currentCase.LoanedVehicle__c = null;
            update currentCase;
        }
        if (loanedVehicle != null) {
            loanedVehicle.Status__c = 'Available';
            loanedVehicle.LoanedTo__c = null;
            loanedVehicle.LoanEndDate__c = null;
            loanedVehicle.LoanStartDate__c = null;
            update loanedVehicle;
        }

    }

}