force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Colour__c.field-meta.xml
<CustomField>
    <fullName>Colour__c</fullName>
    <label>Colour</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Multicolour</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Brown</fullName>
            </value>
            <value>
                <fullName>Grey</fullName>
            </value>
            <value>
                <fullName>Beige</fullName>
            </value>
            <value>
                <fullName>Metalic</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>lookup contact</description>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Vehicles</relationshipLabel>
    <relationshipName>Vehicles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/EndDate__c.field-meta.xml
<CustomField>
    <fullName>EndDate__c</fullName>
    <label>Loan end date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/EngineCapacity__c.field-meta.xml
<CustomField>
    <fullName>EngineCapacity__c</fullName>
    <label>Engine Capacity</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>Austin</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Cadillac</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Chrysler</fullName>
            </value>
            <value>
                <fullName>Citroen</fullName>
            </value>
            <value>
                <fullName>Abarth</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>Acura</fullName>
            </value>
            <value>
                <fullName>Aixam</fullName>
            </value>
            <value>
                <fullName>Alpina</fullName>
            </value>
            <value>
                <fullName>Alpine</fullName>
            </value>
            <value>
                <fullName>AMC</fullName>
            </value>
            <value>
                <fullName>AMG</fullName>
            </value>
            <value>
                <fullName>APAL</fullName>
            </value>
            <value>
                <fullName>Ariel</fullName>
            </value>
            <value>
                <fullName>ARO</fullName>
            </value>
            <value>
                <fullName>Aston Martin</fullName>
            </value>
            <value>
                <fullName>Autobianchi</fullName>
            </value>
            <value>
                <fullName>Auverland</fullName>
            </value>
            <value>
                <fullName>Bauchet</fullName>
            </value>
            <value>
                <fullName>Bentley</fullName>
            </value>
            <value>
                <fullName>Bertone</fullName>
            </value>
            <value>
                <fullName>Bristol</fullName>
            </value>
            <value>
                <fullName>Bugatti</fullName>
            </value>
            <value>
                <fullName>Buick</fullName>
            </value>
            <value>
                <fullName>Caterham</fullName>
            </value>
            <value>
                <fullName>Checker</fullName>
            </value>
            <value>
                <fullName>Cobra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/RegistrationNumber__c.field-meta.xml
<CustomField>
    <fullName>RegistrationNumber__c</fullName>
    <externalId>true</externalId>
    <label>Registration number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Loan start date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>available</fullName>
            </value>
            <value>
                <fullName>loaned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/TotalLoss__c.field-meta.xml
<CustomField>
    <fullName>Totalloss__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Total loss</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Warranty__c.field-meta.xml
<CustomField>
    <fullName>Warranty__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Warranty</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/YearVehicle__c.field-meta.xml
<CustomField>
    <fullName>YearVehicle__c</fullName>
    <label>Year of Vehicle</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/recordTypes/CustomerVehicle.recordType-meta.xml
<RecordType>
    <fullName>CustomerVehicle</fullName>
    <active>true</active>
    <label>Customer Vehicle</label>
</RecordType>

force-app/main/default/objects/Vehicle__c/recordTypes/LoanedVehicle.recordType-meta.xml
<RecordType>
    <fullName>LoanedVehicle</fullName>
    <active>true</active>
    <label>Loaned Vehicle</label>
</RecordType>

force-app/main/default/classes/LWC01_DetailScreen.cls
public with sharing class LWC01_DetailScreen {

    @AuraEnabled
    public static Vehicle__c customerVehicle(Id recordId){
        Case myCase = [SELECT Vehicle__c FROM Case WHERE Id =: recordId];
        Vehicle__c customerVehicle = [SELECT Colour__c, Description__c,EndDate__c,StartDate__c,
        Make__c,EngineCapacity__c, Mileage__c, Model__c,
        RegistrationNumber__c, status__c, TotalLoss__c,
        Name, Warranty__c, YearVehicle__c FROM Vehicle__c WHERE Id =: myCase.Vehicle__c
        AND Recordtype.Name = 'Customer Vehicle'];
        return customerVehicle;
    }

    @AuraEnabled
    public static Vehicle__c loanedVehicle(Id recordId){
        Case myCase = [SELECT ContactId FROM Case WHERE Id =: recordId];
        Vehicle__c loanedVehicle = [SELECT Colour__c, Description__c,
         Make__c, EngineCapacity__c,Mileage__c, Model__c,
         RegistrationNumber__c,EndDate__c,StartDate__c,status__c,TotalLoss__c,
        Name, Warranty__c, YearVehicle__c FROM Vehicle__c WHERE Contact__c =: myCase.ContactId
        AND Recordtype.Name = 'Loaned Vehicle'];
        return loanedVehicle;
    }
}