force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/RegistrationNumber__c.field-meta.xml
<CustomField>
    <fullName>RegistrationNumber__c</fullName>
    <externalId>true</externalId>
    <label>Registration number</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AP04_GetVehicleDetails.cls
/**
 * @description       : 
 * @author            : Narmeen Nehor
 * @group             : 
 * @last modified on  : 02/11/2022
 * @last modified by  : Narmeen Nehor 
 * Modifications Log
 * Ver   Date         Author          Modification
 * 1.0   02/11/2022   Narmeen Nehor   Initial Version
**/
public with sharing class AP04_GetVehicleDetails {
    public static map<String, List<Vehicle__c>> getVehDetails(List<Case> lstCas, List<Id> lstVehIds){

        System.debug('lstCas' + lstCas);

        Map<String, List<Vehicle__c>> mapRecTypeToCase = new Map<String, List<Vehicle__c>>();

        for (Vehicle__c veh: [SELECT Id, Name, RegistrationNumber__c, Model__c, RecordType.DeveloperName FROM Vehicle__c WHERE Id IN: lstVehIds]){

            System.debug('In loop case details' + veh);

            if (mapRecTypeToCase.containsKey(veh.RecordType.DeveloperName)){
                mapRecTypeToCase.get(veh.RecordType.DeveloperName).add(veh);
            }
            else{
                mapRecTypeToCase.put(veh.RecordType.DeveloperName, new List<Vehicle__c>{veh});
            }
        }

        System.debug('<<<<<<<<<<' + mapRecTypeToCase);

        return mapRecTypeToCase;
    }
}