force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/LoanEndDate__c.field-meta.xml
<CustomField>
    <fullName>LoanEndDate__c</fullName>
    <label>Loan End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>Austin</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Cadillac</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Chrysler</fullName>
            </value>
            <value>
                <fullName>Citroen</fullName>
            </value>
            <value>
                <fullName>Abarth</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>Acura</fullName>
            </value>
            <value>
                <fullName>Aixam</fullName>
            </value>
            <value>
                <fullName>Alpina</fullName>
            </value>
            <value>
                <fullName>Alpine</fullName>
            </value>
            <value>
                <fullName>AMC</fullName>
            </value>
            <value>
                <fullName>AMG</fullName>
            </value>
            <value>
                <fullName>APAL</fullName>
            </value>
            <value>
                <fullName>Ariel</fullName>
            </value>
            <value>
                <fullName>ARO</fullName>
            </value>
            <value>
                <fullName>Aston Martin</fullName>
            </value>
            <value>
                <fullName>Autobianchi</fullName>
            </value>
            <value>
                <fullName>Auverland</fullName>
            </value>
            <value>
                <fullName>Bauchet</fullName>
            </value>
            <value>
                <fullName>Bentley</fullName>
            </value>
            <value>
                <fullName>Bertone</fullName>
            </value>
            <value>
                <fullName>Bristol</fullName>
            </value>
            <value>
                <fullName>Bugatti</fullName>
            </value>
            <value>
                <fullName>Buick</fullName>
            </value>
            <value>
                <fullName>Caterham</fullName>
            </value>
            <value>
                <fullName>Checker</fullName>
            </value>
            <value>
                <fullName>Cobra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LWC02_VehicleController.cls
/**
 * @description       : 
 * @author            : Sambhav Bholah
 * @group             : 
 * @last modified on  : 11-03-2022
 * @last modified by  : Sambhav Bholah
**/
public with sharing class LWC02_VehicleController {
    @AuraEnabled(cacheable=true)

    public static List<Vehicle__c> getRelatedLoanedVehicles(Id recordId){

        List<Case> lstCurrentCase = [SELECT  LoanToVehicle__c FROM Case WHERE Id =: recordId];
        
        List<Vehicle__c> lstVehicleLoaned = [SELECT Make__c, 	Model__c, LoanEndDate__c FROM Vehicle__c WHERE Id =: lstCurrentCase[0].LoanToVehicle__c];
        system.debug('this is loaned vehicle' + lstVehicleLoaned);
        
        return lstVehicleLoaned;
    }


    public static List<Case> terminateLoan(ID recordId){
        List<Case> lstCurrentCase = [SELECT LoanToVehicle__c FROM Case WHERE Id =: recordId];
        return lstCurrentCase;
        // List<Vehicle__c> lstVehicle = [SELECT Id, LoanEndDate__c FROM Vehicle__c WHERE Id =: lstCurrentCase[0].LoanToVehicle__c];
        // system.debug('before');
        // system.debug(lstVehicle);
        // for(Vehicle__c lstVehicle: veh){
        //     veh.LoanEndDate__c = NULL;
        // }

        // If(lstVehicle.size()>0){
        //     UPDATE lstVehicle
        // }

        //system.debug('after');
        //system.debug(lstVehicle);
        //return lstVehicle;
    }

}