force-app/main/default/objects/Vehicle__c/Vehicle__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicle__c/fields/LoanEndDate__c.field-meta.xml
<CustomField>
    <fullName>LoanEndDate__c</fullName>
    <label>Loan End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>Austin</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Cadillac</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Chrysler</fullName>
            </value>
            <value>
                <fullName>Citroen</fullName>
            </value>
            <value>
                <fullName>Abarth</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>Acura</fullName>
            </value>
            <value>
                <fullName>Aixam</fullName>
            </value>
            <value>
                <fullName>Alpina</fullName>
            </value>
            <value>
                <fullName>Alpine</fullName>
            </value>
            <value>
                <fullName>AMC</fullName>
            </value>
            <value>
                <fullName>AMG</fullName>
            </value>
            <value>
                <fullName>APAL</fullName>
            </value>
            <value>
                <fullName>Ariel</fullName>
            </value>
            <value>
                <fullName>ARO</fullName>
            </value>
            <value>
                <fullName>Aston Martin</fullName>
            </value>
            <value>
                <fullName>Autobianchi</fullName>
            </value>
            <value>
                <fullName>Auverland</fullName>
            </value>
            <value>
                <fullName>Bauchet</fullName>
            </value>
            <value>
                <fullName>Bentley</fullName>
            </value>
            <value>
                <fullName>Bertone</fullName>
            </value>
            <value>
                <fullName>Bristol</fullName>
            </value>
            <value>
                <fullName>Bugatti</fullName>
            </value>
            <value>
                <fullName>Buick</fullName>
            </value>
            <value>
                <fullName>Caterham</fullName>
            </value>
            <value>
                <fullName>Checker</fullName>
            </value>
            <value>
                <fullName>Cobra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicle__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AP10_customerVehicleController.cls
/**
 * @description       : 
 * @author            : Bhoovanyu Dhomah
 * @group             : 
 * @last modified on  : 11-03-2022
 * @last modified by  : Bhoovanyu Dhomah
 * Modifications Log
 * Ver   Date         Author             Modification
 * 1.0   11-03-2022   Bhoovanyu Dhomah   Initial Version
**/
public with sharing class AP10_customerVehicleController {
    @AuraEnabled(cacheable=true)
    public static Case getCustomerVeh(Id recordId){

        List<Case> lstCas = [SELECT DamagedVehicle__c, DamagedVehicle__r.Model__c,DamagedVehicle__r.Make__c FROM Case WHERE Id =:recordId];

        return lstCas[0];
        // Set<Id> setVehId = new Set<Id>();
        // setVehId.add(lstCas[0].DamagedVehicle__c);
        // setVehId.add(lstCas[0].LoanedVehicle__c);

        // List<Vehicle__c> lstVeh = [SELECT Model__c, Make__c FROM Vehicle__c WHERE Id=:vehId];
        // List<Vehicle__c> lstVeh = [SELECT LoanEndDate__c, Vehicle__c.RecordType.DeveloperName, Model__c, Make__c FROM Vehicle__c WHERE Id IN :setVehId ];

        // List<Vehicle__c> lstVehOrdered = new List<Vehicle__c>();
        // lstVehOrdered[0].add(new Vehicle__c());

        // // System.debug(lstVeh);
        // System.debug('damaged vehicle '+lstVeh);
        // System.debug('damaged vehicle details '+lstVeh[0].RecordType.DeveloperName);
        // return lstVeh[0];
    }
}