force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>invoices</relationshipLabel>
    <relationshipName>invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LC01_CaseRelatedInvoiceCtrl.cls
public class LC01_CaseRelatedInvoiceCtrl {
	
    @AuraEnabled(cacheable=false)
    public static List<Invoice__c> getRelatedInvoices(String caseId) {
        System.debug('caseId -> ' + caseId);

        List<Invoice__c> lstInvoice = new List<Invoice__c>();
        try{
            lstInvoice = [SELECT id, Name FROM Invoice__c WHERE Case__c =: caseId ORDER BY CreatedDate DESC];
        }catch(Exception ex){
            System.debug('An exception occurred:'+ex.getMessage());
        }
        
        return lstInvoice;
    }
}