force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>invoices</relationshipLabel>
    <relationshipName>invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EmailTriggerHandler.cls
/**
 * @File Name          : EmailTriggerHandler.cls
 * @Description        : handler for EmailTrigger
 * @Author             : Bhavish Nundoo
 * @Group              :
 * @Last Modified By   : Bhavish Nundoo
 * @Last Modified On   : 10-25-2022
 * @Modification Log   :
 *==============================================================================
 * Ver         Date                     Author      Modification
 *==============================================================================
 * 1.0    25/10/2022, HH:MM:SS      BNU      Initial Version
 **/
public with sharing class EmailTriggerHandler {

    /**
     * @description Method .
     * @author Bhavish Nundoo | 25/10/2022
     * @return String The managed object's name.
     **/
    public void handlerAfterInsert(List <Invoice__c> lstInvInc){
        List<Invoice__c> lstinvContact = new List<Invoice__c>();
        
        for (Invoice__c inv : lstInvInc) {
            if (inv.Contact__c != null) {
                lstinvContact.add(inv);
            }
        }
        if(lstinvContact.size()>0){
            AP02_SendEmail.sendMail(lstinvContact);
        }

    }


}