force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AmountWithVat__c.field-meta.xml
<CustomField>
    <fullName>AmountWithVat__c</fullName>
    <formula>( AmountwithoutVat__c *  Vat__c ) +  AmountwithoutVat__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount with Vat</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>invoices</relationshipLabel>
    <relationshipName>invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>invoices</relationshipLabel>
    <relationshipName>invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/invoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>invoiceNumber__c</fullName>
    <displayFormat>A-{0000}</displayFormat>
    <label>invoice Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/LastPaymentDate__c.field-meta.xml
<CustomField>
    <fullName>LastPaymentDate__c</fullName>
    <label>Last Payment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/AP06_mail.cls
/**
 * @description       :
 * @author            : Keny Poisson
 * @group             :
 * @last modified on  : 10-25-2022
 * @last modified by  : Keny Poisson
 * Modifications Log
 * Ver   Date         Author         Modification
 * 1.0   10-25-2022   Keny Poisson   Initial Version
 **/
public with sharing class AP06_mail {

  public static void sendEmail (List<invoice__c> lstInvoice) {
    for (invoice__c inv : lstInvoice) {
      Decimal AmountInclVat = inv.AmountWithVat__c;
      String CaseType = inv.Case__r.Type;
      String Reason = inv.Case__r.Reason;
      Datetime PaymentDate = inv.LastPaymentDate__c;
      String RegMark = inv.Case__r.DamageVehicle__r.RegistrationNumber__c;
      String Email = inv.Contact__r.Email__c;
      String invNum= inv.invoiceNumber__c;

      System.debug('Reason and case type: ' + CaseType + Reason);

      Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
      message.toAddresses = new List<String>{'keny.poisson@spoonconsulting.com'};
      message.optOutPolicy = 'FILTER';
      message.subject = 'Ti Vitesse: Invoice: '+ invNum;
      message.plainTextBody = 'Amount incl Vat: ' + AmountInclVat;
      Messaging.SingleEmailMessage[] messages = new List<Messaging.SingleEmailMessage>{
        message
      };
      Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);

      System.debug('Pass Constructor');

      if (results[0].success) {
        System.debug('The email was sent successfully.');
      } else {
        System.debug('The email failed to send: ' + results[0].errors[0].message);
      }
    }
    System.debug(lstInvoice);
  }
}