force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/LastPaymentDate__c.field-meta.xml
<CustomField>
    <fullName>LastPaymentDate__c</fullName>
    <label>Last Payment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/InvoiceTriggerDeleteHandler.cls
/**
 * @description       : 
 * @author            : Narmeen Nehor
 * @group             : 
 * @last modified on  : 26/10/2022
 * @last modified by  : Narmeen Nehor
 * Modifications Log
 * Ver   Date         Author          Modification
 * 1.0   26/10/2022   Narmeen Nehor   Initial Version
**/
public with sharing class InvoiceTriggerDeleteHandler {
    public void handlerBeforeDelete (List<Invoice__c> lstInvDel) {
        List<Invoice__c> lstInvWithPaymt = new List<Invoice__c>();
        for (invoice__c inv : lstInvDel) {
            if(inv.LastPaymentDate__c!= null){
                if(inv.LastPaymentDate__c > System.now()){
                lstInvWithPaymt.add(inv);
            }

            }
            
        }
        if (lstInvWithPaymt.size()>0) {
            AP03_PreventDeletion.preventInvDel(lstInvWithPaymt);
        }

    }
}