force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>invoices</relationshipLabel>
    <relationshipName>invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/AmountWithoutVat__c.field-meta.xml
<CustomField>
    <fullName>AmountwithoutVat__c</fullName>
    <label>Amount without Vat</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/AmountWithVat__c.field-meta.xml
<CustomField>
    <fullName>AmountWithVat__c</fullName>
    <formula>( AmountwithoutVat__c *  Vat__c ) +  AmountwithoutVat__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount with Vat</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>invoices</relationshipLabel>
    <relationshipName>invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>invoices</relationshipLabel>
    <relationshipName>invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/InvoiceDate__c.field-meta.xml
<CustomField>
    <fullName>InvoiceDate__c</fullName>
    <label>Invoice Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/LC01_InvoiceControllerTest2.cls
/**
 * @description       : 
 * @author            : Ayman Rummun
 * @group             : 
 * @last modified on  : 11-08-2022
 * @last modified by  : Ayman Rummun
 * Modifications Log
 * Ver   Date         Author         Modification
 * 1.0   11-08-2022   Ayman Rummun   Initial Version
**/
@isTest
public with sharing class LC01_InvoiceControllerTest2 {
    @TestSetup 
    static void testSetup(){
        List<User> lstUser = AP_TestDataFactory.createUser(1);
        INSERT lstUser;

        List<Case> lstCas = AP_TestDataFactory.createCase(1);
        INSERT lstCas;

        List<Invoice__c> lstinv= AP_TestDataFactory.createInvoice(1);
        lstinv[0].Case__c=lstCas[0].Id;
        INSERT lstinv;
    }

    @isTest 
    static void testGetInvoice()
    {
        List<Case> lstCas = [SELECT Id FROM Case];
        List<Invoice__c> lstInv = LC01_DisplayInvoicesController.getInvoices(lstCas[0].Id);
        System.assertEquals(1, lstInv.size(), 'one invoice inserted');
        System.debug('Size of invoice list: ' + lstInv.size());
    }

    @isTest 
    public static void testGetInvoice2() {
        List<Case> lstCase = new List<Case>();
        List<Invoice__c> lstInv = new List<Invoice__c>();

        List<User> lstUsers = [SELECT Id FROM USER WHERE LastName='Testing' ];
        System.runas(lstUsers[0]){
            Test.startTest();
            lstCase = [SELECT Id FROM Case WHERE Status ='Payment'];
            lstInv = LC01_DisplayInvoicesController.getInvoices(lstCase[0].Id);
            //lstInv = LC01_DisplayInvoicesController.getInvoice('test'); // forwrong
            List<Invoice__c> lstInv2 = [
                SELECT
                  Name,
                  AmountWithVat__c,
                  InvoiceDate__c,
                  Account__c,
                  AmountWithoutVat__c,
                  Contact__c
                FROM Invoice__c
                WHERE Case__c = :lstCase[0].Id
                ORDER BY CreatedDate DESC
              ];
             
            Test.stopTest();
            System.assertEquals(lstInv,lstInv2,'good');
            //System.assert( lstInv.size()==0,'wrong'); //for wrong
            //System.assertEquals(1,lstInv2.size(),'good'); // for size
        }
    }
}