force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/LastPaymentDate__c.field-meta.xml
<CustomField>
    <fullName>LastPaymentDate__c</fullName>
    <label>Last Payment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/AP05_EnableDeletionOfInvoice.cls
/**
 * @description       : 
 * @author            : Ayman Rummun
 * @group             : 
 * @last modified on  : 10-26-2022
 * @last modified by  : Ayman Rummun
 * Modifications Log
 * Ver   Date         Author         Modification
 * 1.0   10-25-2022   Ayman Rummun   Initial Version
**/
public with sharing class AP05_EnableDeletionOfInvoice {
    public static void unenableDeletionOfInvoiceIfPaymentDateIsBeforeLastDate(List<Invoice__c> lstInv) {

        //List<Invoice__c> lstInvGetRec = [SELECT LastPaymentDate__c FROM Invoice__c WHERE Id IN: lstInv];

        for(Invoice__c inv: lstInv)
        {
            if(inv.LastPaymentDate__c !=null){
                if(inv.LastPaymentDate__c > System.now())
                {
                    inv.adderror('Cannot delete invoice before last payment date');
                }
            }
              
        }
    }
}