force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>invoices</relationshipLabel>
    <relationshipName>invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InvoiceTriggerHandler.cls
/**
 * @description       : 
 * @author            : Narmeen Nehor
 * @group             : 
 * @last modified on  : 25/10/2022
 * @last modified by  : Narmeen Nehor
 * Modifications Log
 * Ver   Date         Author          Modification
 * 1.0   25/10/2022   Narmeen Nehor   Initial Version
**/
public with sharing class InvoiceTriggerHandler {
    public void handleAfterInsert(List<Invoice__c> lstInv) {
        List<Invoice__c> lstinvWithContact = new List<Invoice__c>();
        for (Invoice__c inv : lstInv) {
            if (inv.Contact__c != null) {
                lstinvWithContact.add(inv);
            }
        }
        AP02_SendEmail.sendEmail(lstinvWithContact);
    }

}