force-app/main/default/objects/Invoice__c/Invoice__c.object-meta.xml
<CustomObject>
    <label>Invoice</label>
    <nameField>
        <displayFormat>INV-{000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Invoice__c/fields/AmountWithoutVat__c.field-meta.xml
<CustomField>
    <fullName>AmountwithoutVat__c</fullName>
    <label>Amount without Vat</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/AmountWithVat__c.field-meta.xml
<CustomField>
    <fullName>AmountWithVat__c</fullName>
    <formula>( AmountwithoutVat__c *  Vat__c ) +  AmountwithoutVat__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Amount with Vat</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>invoices</relationshipLabel>
    <relationshipName>invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/invoiceNumber__c.field-meta.xml
<CustomField>
    <fullName>invoiceNumber__c</fullName>
    <displayFormat>A-{0000}</displayFormat>
    <label>invoice Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Invoice__c/fields/LastPaymentDate__c.field-meta.xml
<CustomField>
    <fullName>LastPaymentDate__c</fullName>
    <label>Last Payment Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/LC01_RetrieveInvoicesRelatedToCase.cls
/**
 * @description       : 
 * @author            : Kanigan Somadoo
 * @group             : 
 * @last modified on  : 10-28-2022
 * @last modified by  : Kanigan Somadoo
 * Modifications Log
 * Ver   Date         Author            Modification
 * 1.0   10-28-2022   Kanigan Somadoo   Initial Version
**/
public with sharing class LC01_RetrieveInvoicesRelatedToCase {
    
    @AuraEnabled
    public static List<Invoice__c> getInvoices(String caseId){

        List<Invoice__c> lstInvoice = [SELECT Name, InvoiceNumber__c, AmountWithoutVat__c,AmountWithVat__c, LastPaymentDate__c
        FROM Invoice__c
        WHERE Case__c = :caseId
        ORDER BY CreatedDate DESC];
    
        return lstInvoice;
    }
}