force-app/main/default/objects/Vehicles__c/Vehicles__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicles__c/fields/LoanEndDate__c.field-meta.xml
<CustomField>
    <fullName>LoanEndDate__c</fullName>
    <label>Loan end date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>Austin</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Cadillac</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Chrysler</fullName>
            </value>
            <value>
                <fullName>Citroen</fullName>
            </value>
            <value>
                <fullName>Abarth</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>Acura</fullName>
            </value>
            <value>
                <fullName>Aixam</fullName>
            </value>
            <value>
                <fullName>Alpina</fullName>
            </value>
            <value>
                <fullName>Alpine</fullName>
            </value>
            <value>
                <fullName>AMC</fullName>
            </value>
            <value>
                <fullName>AMG</fullName>
            </value>
            <value>
                <fullName>APAL</fullName>
            </value>
            <value>
                <fullName>Ariel</fullName>
            </value>
            <value>
                <fullName>ARO</fullName>
            </value>
            <value>
                <fullName>Aston Martin</fullName>
            </value>
            <value>
                <fullName>Autobianchi</fullName>
            </value>
            <value>
                <fullName>Auverland</fullName>
            </value>
            <value>
                <fullName>Bauchet</fullName>
            </value>
            <value>
                <fullName>Bentley</fullName>
            </value>
            <value>
                <fullName>Bertone</fullName>
            </value>
            <value>
                <fullName>Bristol</fullName>
            </value>
            <value>
                <fullName>Bugatti</fullName>
            </value>
            <value>
                <fullName>Buick</fullName>
            </value>
            <value>
                <fullName>Caterham</fullName>
            </value>
            <value>
                <fullName>Checker</fullName>
            </value>
            <value>
                <fullName>Cobra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AP09_getLoanedVehicle.cls
/**
 * @description       : 
 * @author            : Asma Ghanty
 * @group             : 
 * @last modified on  : 11-03-2022
 * @last modified by  : Asma Ghanty
 * Modifications Log
 * Ver   Date         Author        Modification
 * 1.0   11-03-2022   Asma Ghanty   Initial Version
**/
public with sharing class AP09_getLoanedVehicle {

    @AuraEnabled (cacheable=true)
    public static List<Vehicles__c> getLoanedVeh(Id recordId){
        List<Case> lstCurrentCase = [SELECT LoanedVehicle__c FROM Case WHERE Id =: recordId];
        
        List<Vehicles__c> lstVehicle = [SELECT Make__c,  Model__c, LoanEndDate__c FROM Vehicles__c WHERE Id =: lstCurrentCase[0].LoanedVehicle__c];
        system.debug(lstVehicle);
        return lstVehicle;
    }

}