force-app/main/default/objects/Vehicles__c/Vehicles__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicles__c/fields/LoanEndDate__c.field-meta.xml
<CustomField>
    <fullName>LoanEndDate__c</fullName>
    <label>Loan end date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>available</fullName>
                <default>true</default>
                <label>available</label>
            </value>
            <value>
                <fullName>loaned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicles__c/recordTypes/LoanedVehicle.recordType-meta.xml
<RecordType>
    <fullName>LoanedVehicle</fullName>
    <active>true</active>
    <label>Loaned Vehicle</label>
</RecordType>

force-app/main/default/classes/LWC02_TerminateLoan.cls
/**
 * @description       : 
 * @author            : Rayhaan Beeharry
 * @group             : 
 * @last modified on  : 11-07-2022
 * @last modified by  : Rayhaan Beeharry
**/
public with sharing class LWC02_TerminateLoan {
    @AuraEnabled
    public static String removeLoanedVehicle(Id caseId,Vehicles__c loanedVehicle) {
        try {
            Case caseToUpdate = new Case (Id=caseId, LoanedVehicle__c= null);
            update caseToUpdate;
            loanedVehicle.status__c='available';
            loanedVehicle.LoanStartDate__c= null;
            loanedVehicle.LoanEndDate__c= null;
            update loanedVehicle;
            return 'Case: '+caseToUpdate.Id + ' was updated.\nVehicle: '+loanedVehicle.Id+' was updated';
        } catch (Exception e) {
            return 'error';
        }           
    }
}