force-app/main/default/objects/Vehicles__c/Vehicles__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicles__c/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>available</fullName>
                <default>true</default>
                <label>available</label>
            </value>
            <value>
                <fullName>loaned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AP04_PreventCreationOfCase.cls
/**
 * @description       :
 * @author            : Ashita Gopaul
 * @group             :
 * @last modified on  : 10-26-2022
 * @last modified by  : Ashita Gopaul
 **/
public with sharing class AP04_PreventCreationOfCase {
    public static void preventCreation(List<Case> lstCasVeh) {
        if (lstCasVeh.size() > 0) {
            List<Id> lstVehIds = new List<Id>();

            for (Case cas : lstCasVeh) {
                lstVehIds.add(cas.LoanedVehicle__c);
            }

            Map<Id, Vehicles__c> mapVeh = new Map<Id, Vehicles__c>([SELECT status__c FROM Vehicles__c WHERE status__c = 'loaned' AND Id IN :lstVehIds]);

            for (Case cas : lstCasVeh) {
                if (mapVeh.containsKey(cas.LoanedVehicle__c)) {
                    cas.addError('Cannot assign vehicle that is already on loan');
                }
            }
        }
    }
}