force-app/main/default/objects/Vehicles__c/Vehicles__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicles__c/fields/Colour__c.field-meta.xml
<CustomField>
    <fullName>Colour__c</fullName>
    <label>Colour</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Multicolour</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Brown</fullName>
            </value>
            <value>
                <fullName>Grey</fullName>
            </value>
            <value>
                <fullName>Beige</fullName>
            </value>
            <value>
                <fullName>Metalic</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>Austin</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Cadillac</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Chrysler</fullName>
            </value>
            <value>
                <fullName>Citroen</fullName>
            </value>
            <value>
                <fullName>Abarth</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>Acura</fullName>
            </value>
            <value>
                <fullName>Aixam</fullName>
            </value>
            <value>
                <fullName>Alpina</fullName>
            </value>
            <value>
                <fullName>Alpine</fullName>
            </value>
            <value>
                <fullName>AMC</fullName>
            </value>
            <value>
                <fullName>AMG</fullName>
            </value>
            <value>
                <fullName>APAL</fullName>
            </value>
            <value>
                <fullName>Ariel</fullName>
            </value>
            <value>
                <fullName>ARO</fullName>
            </value>
            <value>
                <fullName>Aston Martin</fullName>
            </value>
            <value>
                <fullName>Autobianchi</fullName>
            </value>
            <value>
                <fullName>Auverland</fullName>
            </value>
            <value>
                <fullName>Bauchet</fullName>
            </value>
            <value>
                <fullName>Bentley</fullName>
            </value>
            <value>
                <fullName>Bertone</fullName>
            </value>
            <value>
                <fullName>Bristol</fullName>
            </value>
            <value>
                <fullName>Bugatti</fullName>
            </value>
            <value>
                <fullName>Buick</fullName>
            </value>
            <value>
                <fullName>Caterham</fullName>
            </value>
            <value>
                <fullName>Checker</fullName>
            </value>
            <value>
                <fullName>Cobra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/Mileage__c.field-meta.xml
<CustomField>
    <fullName>Mileage__c</fullName>
    <label>Mileage</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/YearOfVehicle__c.field-meta.xml
<CustomField>
    <fullName>YearOfVehicle__c</fullName>
    <label>Year of Vehicle</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AP02_Vehicles.cls
/**
 * @File Name          : AP02_Vehicles.cls
 * @Description        : Apex basics and database day 2
 * @Author             : <Company Name>
 * @Group              : 
 * @Last Modified By   : RBE
 * @Last Modified On   : 10-20-2022
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      Modification
 *==============================================================================
 * 1.0    DD-MMM-YYYY, HH:MM:SS      RBE      Initial Version
**/

public with sharing class AP02_Vehicles {
    /**
     * @description Get all Vehicles having the color passed as parameter
     * @author Rayhaan Beeharry | 10/20/2022
     * @return void.
     **/
    public static void getVehiclesByColor(String color){
        if(String.isBlank(color)){            
            System.debug('No color was specified');
            return;
        }

        List<Vehicles__c> lstVeh= [SELECT Make__c,Model__c,Mileage__c FROM Vehicles__c WHERE Colour__c=: color];
        if(lstVeh.size()==0){
            System.debug('No vehicles were found');
            return;
        }

        for(Vehicles__c v: lstVeh){
            System.debug('Make: '+v.Make__c+' Model: '+v.Model__c+' Mileage: '+v.Mileage__c);
        }        
    }

     /**
     * @description Get all Vehicles having the colors passed as parameter, using a set
     * @author Rayhaan Beeharry | 10/20/2022
     * @return void.
     **/
    public static void getVehiclesSetColor(String col1, String col2){
        Set<String> setColours= new Set<String>();
        setColours.add(col1);
        setColours.add(col2);

        List<Vehicles__c> lstVeh= [SELECT Make__c,Model__c,YearOfVehicle__c FROM Vehicles__c WHERE Colour__c IN :setColours];
        if(lstVeh.size()==0){
            System.debug('No vehicles were found');
            return;
        }

        for(Vehicles__c v: lstVeh){
            System.debug('Make: '+v.Make__c+' Model: '+v.Model__c+' Year of Vehicle: '+v.YearOfVehicle__c);
        }        
    }

    public static void mapExample(){
        Map<String,String> mapRegNumMake= new Map<String,String> ();

        mapRegNumMake.put('12 JN 94','Toyota Glanza');
        mapRegNumMake.put('78 OC 98','Toyota Supra');
        mapRegNumMake.put('1 JN 22','BMW X5 M');
        mapRegNumMake.put('758 OC 00','Honda Civic EK3');

        System.debug('My Cars and their Make: '+ mapRegNumMake);
        System.debug('Map Size: '+mapRegNumMake.size());
    }

    public static void mapExample2(String colour){
        List<String> lstEmployees= new List<String>();
        lstEmployees.add('John');
        lstEmployees.add('Tom');
        lstEmployees.add('Jane');

        List<String> lstEmployees2= new List<String>();
        lstEmployees2.add('Paul');
        lstEmployees2.add('Sarah');
        lstEmployees2.add('Jim');

        Map<String,List<String>> mapClothesColourEmployees= new Map<String, List<String>>();
        mapClothesColourEmployees.put('Blue', lstEmployees);
        mapClothesColourEmployees.put('Red', lstEmployees2);
        //String colour='Red';
        if(mapClothesColourEmployees.containsKey(colour)){
            System.debug('Clothes color  and employee names: '+ mapClothesColourEmployees.get(colour));
            System.debug('Clothes colors: '+ mapClothesColourEmployees.keySet());
            System.debug('Employee names: '+ mapClothesColourEmployees.values());
        }
        Integer numEmployees=0;
        for(String col:mapClothesColourEmployees.keySet()){
            numEmployees+= mapClothesColourEmployees.get(col).size();
        }
        System.debug(numEmployees);

        // numEmployees=0;
        // for(List<String> emps: mapClothesColourEmployees.values()){
        //     numEmployees+=emps.size();
        // }
        // System.debug(numEmployees);
    }
    
    
}