force-app/main/default/objects/Vehicles__c/Vehicles__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicles__c/fields/Colour__c.field-meta.xml
<CustomField>
    <fullName>Colour__c</fullName>
    <label>Colour</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Multicolour</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Brown</fullName>
            </value>
            <value>
                <fullName>Grey</fullName>
            </value>
            <value>
                <fullName>Beige</fullName>
            </value>
            <value>
                <fullName>Metalic</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>Austin</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Cadillac</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Chrysler</fullName>
            </value>
            <value>
                <fullName>Citroen</fullName>
            </value>
            <value>
                <fullName>Abarth</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>Acura</fullName>
            </value>
            <value>
                <fullName>Aixam</fullName>
            </value>
            <value>
                <fullName>Alpina</fullName>
            </value>
            <value>
                <fullName>Alpine</fullName>
            </value>
            <value>
                <fullName>AMC</fullName>
            </value>
            <value>
                <fullName>AMG</fullName>
            </value>
            <value>
                <fullName>APAL</fullName>
            </value>
            <value>
                <fullName>Ariel</fullName>
            </value>
            <value>
                <fullName>ARO</fullName>
            </value>
            <value>
                <fullName>Aston Martin</fullName>
            </value>
            <value>
                <fullName>Autobianchi</fullName>
            </value>
            <value>
                <fullName>Auverland</fullName>
            </value>
            <value>
                <fullName>Bauchet</fullName>
            </value>
            <value>
                <fullName>Bentley</fullName>
            </value>
            <value>
                <fullName>Bertone</fullName>
            </value>
            <value>
                <fullName>Bristol</fullName>
            </value>
            <value>
                <fullName>Bugatti</fullName>
            </value>
            <value>
                <fullName>Buick</fullName>
            </value>
            <value>
                <fullName>Caterham</fullName>
            </value>
            <value>
                <fullName>Checker</fullName>
            </value>
            <value>
                <fullName>Cobra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/Mileage__c.field-meta.xml
<CustomField>
    <fullName>Mileage__c</fullName>
    <label>Mileage</label>
    <precision>6</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AP02_ParameterExercise.cls
/**
 * @description       :
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             :
 * @last modified on  : 10-20-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
 **/
/**
 * @File Name          : AP02_ParameterExercise.cls
 * @Description        : Initialisation with VSCode
 * @Author             : Spoon Consulting
 * @Group              :
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 10-20-2022
 * @Modification Log   :
 *==============================================================================
 * Ver         Date                     Author      Modification
 *==============================================================================
 * 1.0       20/10/22                    AGH       Initial Version
 **/
public with sharing class AP02_ParameterExercise {

    
        /**
        * @description Method that takes as input String color and query the selected fields. Colour should match with the one in the parameter
        * @author Asma Ghanty | 19/10/22
        * @return String The managed object's name.
        **/
        public static void colourMatchVehicle(String color){
            
            List<Vehicles__c> listVehicle = [SELECT Colour__c, Make__c, Model__c, Mileage__c FROM Vehicles__c WHERE Colour__c =: color];


            if (listVehicle.size()>0){
            
                System.debug(listVehicle);
            
            }
          
        }

        /**
        * @description Method that takes as input String color and using Set to assign 2 colours.
        * @author Asma Ghanty | 19/10/22
        * @return String The managed object's name.
        **/

        public static void vehColour(String color){
            Set<String> set1 = new Set <String>{'Red', 'Blue'};
            List<Vehicles__c> lstVehicle = [SELECT Colour__c, Make__c, Model__c, Mileage__c FROM Vehicles__c WHERE Colour__c IN: set1];

            if (lstVehicle.size()>0){
           
                System.debug(lstVehicle);
            
        }

        }

        public static void mapExercise(){
            Map<string, String> mapRegNumMake = new Map<string, String>();

            //add items
            mapRegNumMake.put('12 JN 94', 'Toyota Glanza');
            mapRegNumMake.put('78 0C 98', 'Toyota Supra');
            mapRegNumMake.put('1 JN 22', 'BMW X6 M');
            mapRegNumMake.put('678 DC 00', 'Honda Civic EK3');

            //print the values
            System.debug('My Cars and their make: mapRegNumMake:' +mapRegNumMake);

            //print map size
            System.debug('Map Size: mapRegNumMake' +mapRegNumMake.size());
        }

        public static void mapGetColour(){

            //creating a set and adding a list into it. Both Key(color) and Value(Name) is type string
            Map<string, List<String>> mapColour = new Map<string, List<String>>();
            
            mapColour.put('Black', new List<String>{'Testing', 'op'});
            mapColour.put('Red', new List<String>{'bhav', 'testing'});

            if (mapColour.containsKey('Black')){

            System.debug('Happy employees wearing Black:' +mapColour.get('Black'));
        }
    

    if (mapColour.containsKey('Red')){

        System.debug('Happy employees wearing Red:' +mapColour.get('Red'));
    }
    //returns all colours from the map
System.debug('Different colours:' +mapColour.keySet());

//to display all key and its values from the map
System.debug('All SUPER HAPPY employee names:' +mapColour.Values());

Integer numOfEmployees = 0;

for (String colour : mapColour.keySet()){

    //mapColor.get(colour) returns a list of EXTREMELY happy employees wearing color x
    numOfEmployees += mapColour.get(colour).Size();
}

System.debug('Number of extremely happy employees:' +numOfEmployees);


}


}