force-app/main/default/objects/Vehicles__c/Vehicles__c.object-meta.xml
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{0000}</displayFormat>
        <label>Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Vehicles__c/fields/Colour__c.field-meta.xml
<CustomField>
    <fullName>Colour__c</fullName>
    <label>Colour</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unknown</fullName>
            </value>
            <value>
                <fullName>Multicolour</fullName>
            </value>
            <value>
                <fullName>White</fullName>
            </value>
            <value>
                <fullName>Black</fullName>
            </value>
            <value>
                <fullName>Red</fullName>
            </value>
            <value>
                <fullName>Blue</fullName>
            </value>
            <value>
                <fullName>Green</fullName>
            </value>
            <value>
                <fullName>Yellow</fullName>
            </value>
            <value>
                <fullName>Orange</fullName>
            </value>
            <value>
                <fullName>Brown</fullName>
            </value>
            <value>
                <fullName>Grey</fullName>
            </value>
            <value>
                <fullName>Beige</fullName>
            </value>
            <value>
                <fullName>Metalic</fullName>
            </value>
            <value>
                <fullName>Purple</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/InsuranceEndDate__c.field-meta.xml
<CustomField>
    <fullName>InsuranceEndDate__c</fullName>
    <description>Required only for customer vehicle</description>
    <label>Insurance end date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/InsuranceStartDate__c.field-meta.xml
<CustomField>
    <fullName>InsuranceStartDate__c</fullName>
    <label>Insurance start date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/Make__c.field-meta.xml
<CustomField>
    <fullName>Make__c</fullName>
    <label>Make</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Audi</fullName>
            </value>
            <value>
                <fullName>Austin</fullName>
            </value>
            <value>
                <fullName>BMW</fullName>
            </value>
            <value>
                <fullName>Cadillac</fullName>
            </value>
            <value>
                <fullName>Chevrolet</fullName>
            </value>
            <value>
                <fullName>Chrysler</fullName>
            </value>
            <value>
                <fullName>Citroen</fullName>
            </value>
            <value>
                <fullName>Abarth</fullName>
            </value>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>Acura</fullName>
            </value>
            <value>
                <fullName>Aixam</fullName>
            </value>
            <value>
                <fullName>Alpina</fullName>
            </value>
            <value>
                <fullName>Alpine</fullName>
            </value>
            <value>
                <fullName>AMC</fullName>
            </value>
            <value>
                <fullName>AMG</fullName>
            </value>
            <value>
                <fullName>APAL</fullName>
            </value>
            <value>
                <fullName>Ariel</fullName>
            </value>
            <value>
                <fullName>ARO</fullName>
            </value>
            <value>
                <fullName>Aston Martin</fullName>
            </value>
            <value>
                <fullName>Autobianchi</fullName>
            </value>
            <value>
                <fullName>Auverland</fullName>
            </value>
            <value>
                <fullName>Bauchet</fullName>
            </value>
            <value>
                <fullName>Bentley</fullName>
            </value>
            <value>
                <fullName>Bertone</fullName>
            </value>
            <value>
                <fullName>Bristol</fullName>
            </value>
            <value>
                <fullName>Bugatti</fullName>
            </value>
            <value>
                <fullName>Buick</fullName>
            </value>
            <value>
                <fullName>Caterham</fullName>
            </value>
            <value>
                <fullName>Checker</fullName>
            </value>
            <value>
                <fullName>Cobra</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Model</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Vehicles__c/fields/RegistrationNumber__c.field-meta.xml
<CustomField>
    <fullName>RegistrationNumber__c</fullName>
    <externalId>true</externalId>
    <label>Registration number</label>
    <length>40</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/LW01_ContactController.cls
/**
 * @description       : 
 * @author            : Rayhaan Beeharry
 * @group             : 
 * @last modified on  : 11-04-2022
 * @last modified by  : Rayhaan Beeharry
**/
public with sharing class LW01_ContactController {
    @AuraEnabled(cacheable=true)
    public static List<Vehicles__c> getVehicles(Id contactId){
        try {
            List<Vehicles__c> lstVeh =[SELECT Colour__c,Make__c,Model__c,RegistrationNumber__c,InsuranceEndDate__c,InsuranceStartDate__c 
            FROM Vehicles__c
            WHERE Contact__c =: contactId];
            return lstVeh;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
   
}